// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/confirm": {
    params: {};
  };
  "/beers": {
    params: {};
  };
  "/breweries": {
    params: {};
  };
  "/beer-styles": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/logout" | "/dashboard" | "/confirm" | "/beers" | "/breweries" | "/beer-styles";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/confirm.tsx": {
    id: "routes/confirm";
    page: "/confirm";
  };
  "routes/beers.tsx": {
    id: "routes/beers";
    page: "/beers";
  };
  "routes/breweries.tsx": {
    id: "routes/breweries";
    page: "/breweries";
  };
  "routes/beer-styles.tsx": {
    id: "routes/beer-styles";
    page: "/beer-styles";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/confirm": typeof import("./app/routes/confirm.tsx");
  "routes/beers": typeof import("./app/routes/beers.tsx");
  "routes/breweries": typeof import("./app/routes/breweries.tsx");
  "routes/beer-styles": typeof import("./app/routes/beer-styles.tsx");
};