<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure.Sql</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
        <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
        <PackageReference
            Include="Microsoft.Extensions.Configuration.Abstractions"
            Version="9.0.0"
        />
        <PackageReference
            Include="Microsoft.Extensions.DependencyInjection.Abstractions"
            Version="10.0.0"
        />
    </ItemGroup>
</Project>
