<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Database.Connection</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="NetTopologySuite" Version="2.6.0" />
        <PackageReference Include="NetTopologySuite.IO.SqlServerBytes" Version="2.1.0" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
        <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
        <PackageReference
            Include="Microsoft.Extensions.Configuration.Abstractions"
            Version="10.0.1"
        />
        <PackageReference
            Include="Microsoft.Extensions.DependencyInjection.Abstractions"
            Version="10.0.0"
        />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.Configuration\Infrastructure.Configuration.csproj" />
    </ItemGroup>
</Project>
