<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure.FileUpload</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
        <PackageReference
            Include="Microsoft.Extensions.Configuration.Abstractions"
            Version="10.0.1"
        />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Infrastructure.Configuration\Infrastructure.Configuration.csproj" />
    </ItemGroup>
</Project>
