<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure.Email</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.16.0" />
    </ItemGroup>
</Project>
