<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>API.Core</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference
            Include="Microsoft.AspNetCore.OpenApi"
            Version="9.0.11"
        />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <PackageReference
            Include="FluentValidation.AspNetCore"
            Version="11.3.0"
        />
        <PackageReference Include="MediatR" Version="12.4.1" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Infrastructure\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Domain\Domain.Entities\Domain.Entities.csproj" />
        <ProjectReference Include="..\..\Domain\Domain.Exceptions\Domain.Exceptions.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.Sql\Infrastructure.Sql.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.Jwt\Infrastructure.Jwt.csproj" />
        <ProjectReference Include="..\..\Features\Features.Breweries\Features.Breweries.csproj" />
        <ProjectReference Include="..\..\Features\Features.UserManagement\Features.UserManagement.csproj" />
        <ProjectReference Include="..\..\Features\Features.Auth\Features.Auth.csproj" />
        <ProjectReference Include="..\..\Features\Features.Emails\Features.Emails.csproj" />
        <ProjectReference Include="..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
        <ProjectReference Include="..\..\Shared\Shared.Application\Shared.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>
</Project>
