services:
  sqlserver:
    env_file: ".env.dev"
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dev-env-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqlserverdata-dev:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks:
      - devnet
  database.migrations:
    env_file: ".env.dev"
    image: database.migrations
    container_name: dev-env-database-migrations
    depends_on:
      sqlserver:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Database/Database.Migrations/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
        APP_UID: 1000
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DB_SERVER: "${DB_SERVER}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CLEAR_DATABASE: "true"
    restart: "no"
    networks:
      - devnet

  database.seed:
    env_file: ".env.dev"
    image: database.seed
    container_name: dev-env-database-seed
    depends_on:
      database.migrations:
        condition: service_completed_successfully
      seaweedfs:
        condition: service_started
    build:
      context: ./backend
      dockerfile: Database/Database.Seed/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
        APP_UID: 1000
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DB_SERVER: "${DB_SERVER}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SEAWEEDFS_SERVICE_URL: "${SEAWEEDFS_SERVICE_URL}"
      SEAWEEDFS_ACCESS_KEY_ID: "${SEAWEEDFS_ACCESS_KEY_ID}"
      SEAWEEDFS_SECRET_ACCESS_KEY: "${SEAWEEDFS_SECRET_ACCESS_KEY}"
      SEAWEEDFS_BUCKET: "${SEAWEEDFS_BUCKET}"
    restart: "no"
    networks:
      - devnet

  seaweedfs:
    env_file: ".env.dev"
    image: chrislusf/seaweedfs
    container_name: dev-env-seaweedfs
    ports:
      - "8333:8333" # S3 API
      - "8888:8888" # Filer UI
      - "9333:9333" # Master UI
      - "23646:23646" # Admin UI
    environment:
      AWS_ACCESS_KEY_ID: "${SEAWEEDFS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${SEAWEEDFS_SECRET_ACCESS_KEY}"
      S3_BUCKET: "${SEAWEEDFS_BUCKET}"
    volumes:
      - seaweedfsdata-dev:/data
    restart: unless-stopped
    networks:
      - devnet

volumes:
  sqlserverdata-dev:
    driver: local
  nuget-cache-dev:
    driver: local
  seaweedfsdata-dev:
    driver: local

networks:
  devnet:
    driver: bridge
